services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_init:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: db_init
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      .env
    entrypoint: ["./setup_db" ]

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api
    depends_on:
      db_init:
        condition: service_completed_successfully
    env_file:
      .env
    ports:
      - "8080:8080"
    entrypoint: ["./server"]

volumes:
  postgres_data: