name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start docker containers
      run: docker compose --file docker/compose.yaml up --build -d
      
    - name: Test API
      run: docker run --rm -v "$(pwd)/test/api":/apps -w /apps --network container:api alpine/bruno run