name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start docker containers
      run: docker compose --file docker/compose.yaml up --build -d
      
    - name: Test API
      run: |
        # Check API is up
        docker run --network container:api dwdraju/alpine-curl-jq curl -fsS http://localhost:8080/api/spots
        # Check /spots endpoint response
        docker run --network container:api dwdraju/alpine-curl-jq curl -fsS "http://localhost:8080/api/spots?start=2024-10-12T08:00:00Z&duration=2" | jq .spots | jq 'if .[0].id == 1 then "/spots endpoint OK" else error("/spots endpoint KO") end'
        # Check /spots/best endpoint response