name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the stack
      run: docker compose --file docker/compose.yaml up --build -d
      
    - name: Run the stack
      run: docker run --network container:api curl -v http://localhost:8080/api/spots/