name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the stack
      run: docker compose --file docker/compose.yaml up --build -d
      
    - name: Test API
      run: |
        # Check API is up
        docker run --network container:api dwdraju/alpine-curl-jq -fsS http://localhost:8080/api/spots/
        # Check /spots endpoint response
        docker run --network container:api dwdraju/alpine-curl-jq -s http://localhost:8080 | jq 'if .[0].Id == 1 then "/spots endpoint OK" else error("spots endpoint KO) end'
        # Check /spots/best endpoint response